
# Common sections
defaults: &defaults
  working_directory: ~/aur
  docker:
    - image: imrehg/archlinux-makepkg

updatepackage: &updatepackage
  name: Update packages
  command: sudo pacman -Syu --noconfirm

gitupdate: &gitupdate
  name: Git repo updates
  command: |
    sed -i "s#ssh+git://aur@aur.archlinux.org#https://aur.archlinux.org#" .gitmodules
    git submodule update --init
pkgbuildtest: &pkgbuildtest
  name: Testing PKGBUILD
  command: |
    cd ~/aur/${CIRCLE_JOB}
    namcap PKGBUILD
buildtest: &buildtest
  name: Building package
  command: |
    cd ~/aur/${CIRCLE_JOB}
    makepkg -sci --noconfirm
install_cassandra: &install_cassandra
  name: Build and install cassandra package from aur
  command: |
    cd ~/
    git clone https://aur.archlinux.org/cassandra.git
    cd cassandra
    makepkg -si --noconfirm --skippgpcheck
install_deb2targz: &install_deb2targz
  name: Build and install cassandra package from aur
  command: |
    cd ~/
    git clone https://aur.archlinux.org/deb2targz.git
    cd deb2targz
    makepkg -si --noconfirm

# Main
version: 2
jobs:
  linux-asus-aura:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - run:
          name: add key to pacman
          command: |
            sudo pacman-key --recv-keys A5E9288C4FA415FA
            sudo gpg --recv-keys A5E9288C4FA415FA
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  linux-thermaltake-rgb:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  kairosdb:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - run:
          <<: *install_cassandra
      - run:
          <<: *install_deb2targz
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest

workflows:
  version: 2
  build:
    jobs:
      - linux-asus-aura
      - linux-thermaltake-rgb
      - kairosdb
